server.port=8888
app.backend.base-url=http://localhost:8888
spring.web.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/airtick
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.show-sql=true
spring.jackson.property-naming-strategy=SNAKE_CASE
jwt-secret="970b6ffac10e3947eeb4ec5a03edaa0676fce9a56d3bf50de78d187523f6b446"
jwt-expiration-ms=86400000